### ISSUE TITLE
Support for x.com links

### ISSUE THREAD

**Issue by mohitgangwani** [dylanpdx/BetterTwitFix#211] opened 2024-05-26 04:49 UTC
Hello,

With the rebranding of Twitter to X, the links are now also copied as x.com rather than twitter.com. This change affects how links are handled by the vxtwitter service.

**Question**

Will there be support for x.com links in vxtwitter, or will we need to continue renaming the domain to twitter.com?

Thank you!

**Comment by dylanpdx** [comment] 2024-05-26 13:39
Please look at previous issues before opening a new one, as this is a duplicate of #156 and #142
You can add "fixv" to x.com links (or replace x.com with fixvx.com) so that they work with x.com URLs

**Closed by dylanpdx** 2024-05-26 13:39 UTC
