### ISSUE TITLE
Failed to scan your tweet

### ISSUE THREAD

**Issue by Ashuraman666** [dylanpdx/BetterTwitFix#74] opened 2023-04-08 12:51 UTC
As of today, no matter what tweet I try to post on discord with vx, I get the same error for all of them
![Sem Título](https://user-images.githubusercontent.com/50785415/230722118-994027c3-bb85-401f-877c-8eefabf5d37e.png)
This happens on every tweet

**Comment by Nama** [comment] 2023-04-08 13:02
This should happen only on some NSFW tweets.

Twitter changed their API restrictions and doesn't allow access to some NSFW tweets.

**Comment by Ashuraman666** [comment] 2023-04-08 13:24
> This should happen only on some NSFW tweets.
> 
> Twitter changed their API restrictions and doesn't allow access to some NSFW tweets.

Is there any way to know which NSFW tweets it blocks and which it doesn't?

**Comment by dylanpdx** [comment] 2023-04-08 14:41
Can I have an example of a non-working tweet so I can add it to my tests?

**Comment by dylanpdx** [comment] 2023-04-08 14:57
It seems like Twitter is returning 404 (Not found) for some tweets, with a message of "Sorry, that page does not exist."
I'm not sure if this is intentional or as a result of some API limit. I'd expect another error code if this was an API limitation

**Comment by Ashuraman666** [comment] 2023-04-08 15:19
> It seems like Twitter is returning 404 (Not found) for some tweets, with a message of "Sorry, that page does not exist." I'm not sure if this is intentional or as a result of some API limit. I'd expect another error code if this was an API limitation

Here's the thing, I tried the same tweets with a different tweet fix (The one where you replace the i in Twitter with an x) and that one did work

**Comment by dylanpdx** [comment] 2023-04-08 16:32
I have a possible workaround in the works, although I'm not sure how long before Twitter blocks that too

**Comment by dylanpdx** [comment] 2023-04-08 17:22
I've deployed a fix, please double check that the issue is fixed.

It's not a perfect fix since it can fail at times, but this is the most I can do as a temporary patch

**Comment by Ashuraman666** [comment] 2023-04-08 17:32
> I've deployed a fix, please double check that the issue is fixed.
> 
> It's not a perfect fix since it can fail at times, but this is the most I can do as a temporary patch

Seems to be working for images for the most part but for videos it still gives the same "Tweet not found" error

**Comment by dylanpdx** [comment] 2023-04-08 17:46
Might be due to Discord's caching of some links, it should start updating them in around 30 minutes or so
Workaround at the moment is to somehow change the URL so that Discord fetches a fresh copy, adding `?a` at the end usually works

**Comment by dylanpdx** [comment] 2023-04-08 20:47
> > It seems like Twitter is returning 404 (Not found) for some tweets, with a message of "Sorry, that page does not exist."
> 
> This is the standard error for adult-restricted tweets via the 1.1 api, you'll get these if you're account isn't old enough for adult content ![image](https://user-images.githubusercontent.com/12771982/230737323-7ceef8c1-ca58-4b72-8d7a-6f433866097d.png) ![image](https://user-images.githubusercontent.com/12771982/230737348-aecaac09-7680-478c-b612-a75ee95b0974.png)

In the past, I seem to remember it returning a message similar to what Twitter shows while logged out
![image](https://user-images.githubusercontent.com/1337360/230741683-33c1eaf1-3c9c-4a3f-86f0-42db1a95fbcb.png)
but I might be mis-remembering. Either way, this makes it annoying to check if a tweet simply doesn't exist or is just age restricted. Some other 4XX error (403?) would probably be more informative.

I also noticed that this change affected a lot of Twitter's own tools as well, i.e https://publish.twitter.com fails for NSFW tweets.

I'm still unsure if this was a deliberate change or some mistake...

**Comment by dylanpdx** [comment] 2023-04-08 21:27
> I sent you an email earlier regarding this issue but I'm fine with discussing it here henceforth

Oh, your email got sent to spam, I'm so sorry I wasn't able to see it! I'm fine discussing this here from now on

vxTwitter is hosted in the US, so they probably rolled that change out today to that region. I guess switching regions could work, but since Discord's link unfurler servers are also in the US it would probably add latency, and not to mention that Twitter has a high chance of switching it off there as well

How I see it at the moment, there's no way to get info about NSFW tweets using any public API, authentication is required. Both v1.1 and v2 API versions return a 404, as do the internal API's like the GraphQL and `cdn.syndication.twimg.com`. There might be another obscure public API out there but I haven't been able to find anything regarding that. 

Overall a pretty upsetting change but I can see the reasoning behind it. This may be related to the new API pricing as well since it went into effect just recently

**Comment by Delphox** [comment] 2023-04-09 20:58
Yea I can confirm it's not working for videos. Here's an example for a video that fails (its not NSFW but gets detected as such): https://vxtwitter.com/TheFunny_mp4/status/1529475039833337858

**Comment by dylanpdx** [comment] 2023-04-09 21:00
Looking into it - Thanks for the example tweet

**Comment by dylanpdx** [comment] 2023-04-09 21:33
This should be fixed now- Keep in mind Discord might take a while to refresh their link cache (usually up to 30 minutes)

**Comment by Delphox** [comment] 2023-04-09 21:44
That was quick, thanks! Just one small issue, some of those videos are embedding super tiny. Here's another example tweet: https://vxtwitter.com/NightShiftNyx/status/1598396995877699602 (also not NSFW but detected as such, but keep in mind this one is from a NSFW account)

**Comment by dylanpdx** [comment] 2023-04-09 22:15
This should now be fixed as well! Sorry about that, my mistake

**Comment by dylanpdx** [comment] 2023-04-09 22:58
My brain is currently at half capacity haha, I'll (hopefully) put in a cleaner fix for this when I can, and maybe add some test cases for it as well

**Comment by Delphox** [comment] 2023-04-10 00:37
Doesn't seem like the last fix worked... NSFW embeds are still small, including the last example one. I tried the ?a trick to make sure.

**Comment by Delphox** [comment] 2023-04-10 01:16
Oh nevermind I tried changing the username instead and it actually forced Discord to re-fetch it. So it was discord's cache messing it up and just adding ?aaa at the end isn't enough. Thanks again!

**Closed** 2023-04-17 12:19 UTC
