### ISSUE TITLE
Add a new url for X links?

### ISSUE THREAD

**Issue by sheady** [dylanpdx/BetterTwitFix#156] opened 2023-10-15 21:17 UTC
The twitter app now gives me an x.com link when I copy from a tweet. fxtwitter has 'fixupx.com' . Could a second url be added so I don't need to type out vxtwitter every time?

**Comment by dylanpdx** [comment] 2023-10-15 22:14
Duplicate of #142 
tl;dr Replace x.com links with fixvx.com (add fixv at the beginning)

**Closed by dylanpdx** 2023-10-15 22:14 UTC
